name: log4dart_plus
description: Log4Dart Plus is a versatile and highly configurable logging framework for Dart / Flutter applications.
version: 0.0.8
repository: https://github.com/Limeslice-Software-Foundation/log4dart-plus

environment:
  sdk: ^3.6.0

dependencies:
  commons_config: ^0.0.8
  intl: ^0.20.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
